import type {
  Bid,
  ChatMessage,
  ChatThread,
  HelpRequest,
  HelperProfile,
  Job,
  User,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "client-1",
    email: "ada@gmail.com",
    displayName: "Ada Okonkwo",
    role: "client",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "helper-1",
    email: "james@outlook.com",
    displayName: "James Adeyemi",
    role: "helper",
    createdAt: "2026-01-08T10:00:00Z",
  },
  {
    id: "helper-2",
    email: "chioma@yahoo.com",
    displayName: "Chioma Nwosu",
    role: "helper",
    createdAt: "2026-01-09T10:00:00Z",
  },
  {
    id: "helper-3",
    email: "tunde@proton.me",
    displayName: "Tunde Balogun",
    role: "helper",
    createdAt: "2026-01-05T10:00:00Z",
  },
  {
    id: "helper-4",
    email: "fatima@gmail.com",
    displayName: "Fatima Ibrahim",
    role: "helper",
    createdAt: "2026-01-06T10:00:00Z",
  },
  {
    id: "helper-5",
    email: "kemi@icloud.com",
    displayName: "Kemi Ojo",
    role: "helper",
    createdAt: "2026-01-07T10:00:00Z",
  },
];

export const mockHelpers: HelperProfile[] = [
  {
    id: "helper-1",
    userId: "helper-1",
    displayName: "James Adeyemi",
    bio: "Final-year CS student. Tutoring algorithms, web dev, and debugging with clear walkthroughs.",
    specialties: ["Computer Science", "Mathematics"],
    minPrice: 5000,
    rating: 4.9,
    completedJobs: 42,
    available: true,
  },
  {
    id: "helper-2",
    userId: "helper-2",
    displayName: "Chioma Nwosu",
    bio: "Literature & academic writing coach. Feedback-focused — structure, clarity, citations.",
    specialties: ["Writing & Essays", "Languages"],
    minPrice: 4000,
    rating: 4.8,
    completedJobs: 67,
    available: true,
  },
  {
    id: "helper-3",
    userId: "helper-3",
    displayName: "Tunde Balogun",
    bio: "Business & economics peer tutor. Case studies, spreadsheets, and exam prep sessions.",
    specialties: ["Business", "Mathematics"],
    minPrice: 6000,
    rating: 4.7,
    completedJobs: 31,
    available: true,
  },
  {
    id: "helper-4",
    userId: "helper-4",
    displayName: "Fatima Ibrahim",
    bio: "Science lab report guidance and concept reviews for chemistry and biology.",
    specialties: ["Science", "Mathematics"],
    minPrice: 4500,
    rating: 4.6,
    completedJobs: 28,
    available: false,
  },
  {
    id: "helper-5",
    userId: "helper-5",
    displayName: "Kemi Ojo",
    bio: "UI/UX and design project mentor. Figma critiques and portfolio feedback.",
    specialties: ["Design", "Computer Science"],
    minPrice: 7000,
    rating: 5.0,
    completedJobs: 19,
    available: true,
  },
];

export const mockRequests: HelpRequest[] = [
  {
    id: "req-1",
    clientId: "client-1",
    clientName: "Ada Okonkwo",
    title: "Data structures assignment walkthrough",
    description:
      "Need a tutoring session on linked lists and trees for my CSC 201 assignment. Prefer step-by-step explanation, not just answers.",
    category: "Computer Science",
    deadline: "2026-07-20",
    offerPrice: 8000,
    status: "open",
    attachmentNames: ["brief.pdf"],
    attachments: [],
    createdAt: "2026-07-10T09:00:00Z",
  },
  {
    id: "req-2",
    clientId: "client-1",
    clientName: "Ada Okonkwo",
    title: "Essay structure review — African literature",
    description:
      "Looking for feedback on thesis clarity and paragraph flow for a 2000-word essay draft.",
    category: "Writing & Essays",
    deadline: "2026-07-18",
    offerPrice: 5500,
    status: "matched",
    attachmentNames: ["draft-v1.docx"],
    attachments: [],
    createdAt: "2026-07-08T14:00:00Z",
  },
];

export const mockBids: Bid[] = [
  {
    id: "bid-1",
    requestId: "req-1",
    clientId: "client-1",
    helperId: "helper-1",
    helperName: "James Adeyemi",
    offerPrice: 8000,
    status: "pending",
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "bid-2",
    requestId: "req-1",
    clientId: "client-1",
    helperId: "helper-3",
    helperName: "Tunde Balogun",
    offerPrice: 8000,
    status: "pending",
    createdAt: "2026-07-10T10:05:00Z",
  },
  {
    id: "bid-3",
    requestId: "req-2",
    clientId: "client-1",
    helperId: "helper-2",
    helperName: "Chioma Nwosu",
    offerPrice: 5500,
    status: "accepted",
    createdAt: "2026-07-08T15:00:00Z",
  },
];

export const mockJobs: Job[] = [
  {
    id: "job-1",
    requestId: "req-2",
    clientId: "client-1",
    clientName: "Ada Okonkwo",
    helperId: "helper-2",
    helperName: "Chioma Nwosu",
    title: "Essay structure review — African literature",
    description:
      "Looking for feedback on thesis clarity and paragraph flow for a 2000-word essay draft.",
    price: 5500,
    status: "in_progress",
    paymentStatus: "paid",
    requestAttachments: [],
    deliverables: [],
    createdAt: "2026-07-08T16:00:00Z",
    updatedAt: "2026-07-09T11:00:00Z",
  },
  {
    id: "job-2",
    requestId: "req-old-1",
    clientId: "client-1",
    clientName: "Ada Okonkwo",
    helperId: "helper-1",
    helperName: "James Adeyemi",
    title: "Python basics tutoring session",
    description: "One-hour session on loops and functions.",
    price: 6000,
    status: "completed",
    paymentStatus: "released",
    requestAttachments: [],
    deliverables: [],
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-02T18:00:00Z",
  },
];

export const mockChats: ChatThread[] = [
  {
    id: "chat-1",
    requestId: "req-1",
    bidId: "bid-1",
    clientId: "client-1",
    helperId: "helper-1",
    helperName: "James Adeyemi",
    clientName: "Ada Okonkwo",
    title: "Data structures assignment walkthrough",
    status: "open",
    lastMessage: "I can do a 90-minute session tomorrow evening.",
    updatedAt: "2026-07-10T12:00:00Z",
  },
  {
    id: "chat-2",
    requestId: "req-2",
    bidId: "bid-3",
    clientId: "client-1",
    helperId: "helper-2",
    helperName: "Chioma Nwosu",
    clientName: "Ada Okonkwo",
    title: "Essay structure review — African literature",
    status: "open",
    lastMessage: "I've annotated section 2 — check the shared notes.",
    updatedAt: "2026-07-09T16:30:00Z",
  },
];

export const mockMessages: Record<string, ChatMessage[]> = {
  "chat-1": [
    {
      id: "m1",
      chatId: "chat-1",
      senderId: "client-1",
      senderName: "Ada Okonkwo",
      text: "Hi James — I bid on your profile for the data structures help. Are you free this week?",
      createdAt: "2026-07-10T10:10:00Z",
    },
    {
      id: "m2",
      chatId: "chat-1",
      senderId: "helper-1",
      senderName: "James Adeyemi",
      text: "I can do a 90-minute session tomorrow evening.",
      createdAt: "2026-07-10T12:00:00Z",
    },
  ],
  "chat-2": [
    {
      id: "m3",
      chatId: "chat-2",
      senderId: "helper-2",
      senderName: "Chioma Nwosu",
      text: "I've annotated section 2 — check the shared notes.",
      createdAt: "2026-07-09T16:30:00Z",
    },
    {
      id: "m4",
      chatId: "chat-2",
      senderId: "client-1",
      senderName: "Ada Okonkwo",
      text: "Thank you! Working through your comments now.",
      createdAt: "2026-07-09T17:00:00Z",
    },
  ],
};
